on:
    pull_request:
        types:
            - opened

jobs:
    pr-action:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Post Docker Action PR Comment
              uses: geast16/docker-action-pr-giphy-comment@main
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

            - name: KodeKloud Giphy PR Comment 9421
              uses: geast16/js-action-pr-giphy-comment@1.0.0-beta
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
